/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as SettingsServerImport } from './routes/settings/server'
import { Route as SettingsRolesImport } from './routes/settings/roles'
import { Route as SettingsMembersImport } from './routes/settings/members'
import { Route as SettingsAccountImport } from './routes/settings/account'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsIndexRoute = SettingsIndexImport.update({
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsServerRoute = SettingsServerImport.update({
  path: '/server',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsRolesRoute = SettingsRolesImport.update({
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsMembersRoute = SettingsMembersImport.update({
  path: '/members',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsAccountRoute = SettingsAccountImport.update({
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/settings/account': {
      preLoaderRoute: typeof SettingsAccountImport
      parentRoute: typeof SettingsImport
    }
    '/settings/members': {
      preLoaderRoute: typeof SettingsMembersImport
      parentRoute: typeof SettingsImport
    }
    '/settings/roles': {
      preLoaderRoute: typeof SettingsRolesImport
      parentRoute: typeof SettingsImport
    }
    '/settings/server': {
      preLoaderRoute: typeof SettingsServerImport
      parentRoute: typeof SettingsImport
    }
    '/settings/': {
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof SettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  ProfileRoute,
  SettingsRoute.addChildren([
    SettingsAccountRoute,
    SettingsMembersRoute,
    SettingsRolesRoute,
    SettingsServerRoute,
    SettingsIndexRoute,
  ]),
])

/* prettier-ignore-end */
